// <auto-generated />
using System;
using Empodera.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsEmpodera.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Empodera.Models.Acoes", b =>
                {
                    b.Property<int>("IdAcoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAtividade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAcoes");

                    b.HasIndex("FkIdAtividade");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("Empodera.Models.AcoesAtores", b =>
                {
                    b.Property<int>("IdAAtores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAcoes")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAAtores");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdAcoes");

                    b.ToTable("AcoesAtores");
                });

            modelBuilder.Entity("Empodera.Models.AnexosDiario", b =>
                {
                    b.Property<int>("IdAnexos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdDiario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAnexos");

                    b.HasIndex("FkIdDiario");

                    b.ToTable("AnexosDiario");
                });

            modelBuilder.Entity("Empodera.Models.Atividades", b =>
                {
                    b.Property<int>("IdAtividade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkIdUsuarioM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAtividade");

                    b.HasIndex("FkIdComunidade");

                    b.HasIndex("FkIdUsuarioM");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("Empodera.Models.AtividadesEixo", b =>
                {
                    b.Property<int>("IdAEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAtividade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdEixo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAEixo");

                    b.HasIndex("FkIdAtividade");

                    b.HasIndex("FkIdEixo");

                    b.ToTable("AtividadesEixo");
                });

            modelBuilder.Entity("Empodera.Models.AtorComunidade", b =>
                {
                    b.Property<int>("IdAtorComunidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAtorComunidade");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdComunidade");

                    b.ToTable("AtorComunidades");
                });

            modelBuilder.Entity("Empodera.Models.Atores", b =>
                {
                    b.Property<int>("IdAtores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkIdUsuarioM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lopiniao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Mcomunidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelSocial1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelSocial2")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAtores");

                    b.HasIndex("FkIdUsuarioM");

                    b.ToTable("Atores");
                });

            modelBuilder.Entity("Empodera.Models.AvaliacaoPessoal", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssBasica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CCrimes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Educacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lazer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Moradia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocupacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prevencao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saude")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Substancias")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("AvaliacaoPessoal");
                });

            modelBuilder.Entity("Empodera.Models.Comunidade", b =>
                {
                    b.Property<int>("Id_Comunidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao_Acessibilidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dt_Criacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dt_Modificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_Id_Usuario")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FK_Id_UsuarioM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Comunidade");

                    b.HasIndex("FK_Id_UsuarioM");

                    b.ToTable("Comunidades");
                });

            modelBuilder.Entity("Empodera.Models.DAAtores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDDacoes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdDDacoes");

                    b.ToTable("DAAtores");
                });

            modelBuilder.Entity("Empodera.Models.DetalhesDAcoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDDacoes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FkIdDDacoes");

                    b.ToTable("DetalhesDAcoes");
                });

            modelBuilder.Entity("Empodera.Models.DetalhesEixos", b =>
                {
                    b.Property<int>("IdDiarioEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDetalhes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdEixo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDiarioEixo");

                    b.HasIndex("FkIdDetalhes");

                    b.HasIndex("FkIdEixo");

                    b.ToTable("DetalhesEixos");
                });

            modelBuilder.Entity("Empodera.Models.DiarioAcoes", b =>
                {
                    b.Property<int>("IdDAcoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAcoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDiario")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDAcoes");

                    b.HasIndex("FkIdAcoes");

                    b.HasIndex("FkIdDiario");

                    b.ToTable("DiarioAcoes");
                });

            modelBuilder.Entity("Empodera.Models.DiarioCampo", b =>
                {
                    b.Property<int>("IdDCampo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDCampo");

                    b.HasIndex("FkIdComunidade");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("DiariosCampo");
                });

            modelBuilder.Entity("Empodera.Models.DiarioDAcoes", b =>
                {
                    b.Property<int>("IdDAcoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDiario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeovedorEx")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDAcoes");

                    b.HasIndex("FkIdDiario");

                    b.ToTable("DiarioDAcoes");
                });

            modelBuilder.Entity("Empodera.Models.DiarioEixo", b =>
                {
                    b.Property<int>("IdDiarioEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdDiario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdEixo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDiarioEixo");

                    b.HasIndex("FkIdDiario");

                    b.HasIndex("FkIdEixo");

                    b.ToTable("DiarioEixos");
                });

            modelBuilder.Entity("Empodera.Models.Eixo", b =>
                {
                    b.Property<int>("IdEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEixo");

                    b.ToTable("Eixos");
                });

            modelBuilder.Entity("Empodera.Models.FichaCondicoes", b =>
                {
                    b.Property<int>("IdCondicoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cond")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdFicha")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCondicoes");

                    b.HasIndex("FkIdFicha");

                    b.ToTable("FichaCondicoes");
                });

            modelBuilder.Entity("Empodera.Models.FichaPeticoes", b =>
                {
                    b.Property<int>("IdPeticoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdFicha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPeticoes");

                    b.HasIndex("FkIdFicha");

                    b.ToTable("FichaPeticoes");
                });

            modelBuilder.Entity("Empodera.Models.FichaPrimeiroContato", b =>
                {
                    b.Property<int>("IdFicha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AEscolar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEstabeleceu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Coment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtContato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emprego")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstaFamiliar")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstruFamiliar")
                        .HasColumnType("TEXT");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FonteDados")
                        .HasColumnType("TEXT");

                    b.Property<string>("FornecidoParceiro")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraContato")
                        .HasColumnType("TEXT");

                    b.Property<string>("LContato")
                        .HasColumnType("TEXT");

                    b.Property<string>("LTrat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NFIlhos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NFilhas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NovoParceiro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QReabili")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SCalc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SComp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SLer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFicha");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdComunidade");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("FichasPrimeiroContato");
                });

            modelBuilder.Entity("Empodera.Models.FichaResp", b =>
                {
                    b.Property<int>("IdCondicoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdFicha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCondicoes");

                    b.HasIndex("FkIdFicha");

                    b.ToTable("FichaRespostas");
                });

            modelBuilder.Entity("Empodera.Models.FichaResult", b =>
                {
                    b.Property<int>("IdCondicoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdFicha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCondicoes");

                    b.HasIndex("FkIdFicha");

                    b.ToTable("FichaResultados");
                });

            modelBuilder.Entity("Empodera.Models.FonteInf", b =>
                {
                    b.Property<int>("IdFonte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AtorIdAtores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdFicha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fk_Id_Ator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelSocial1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PapelSocial2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdFonte");

                    b.HasIndex("AtorIdAtores");

                    b.HasIndex("FkIdFicha");

                    b.ToTable("FontesInfo");
                });

            modelBuilder.Entity("Empodera.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            IdPerfil = 1,
                            DtCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtModificacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkIdUsuario = 1,
                            Nome = "Admin"
                        },
                        new
                        {
                            IdPerfil = 2,
                            DtCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtModificacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkIdUsuario = 2,
                            Nome = "Editor"
                        },
                        new
                        {
                            IdPerfil = 3,
                            DtCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtModificacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkIdUsuario = 3,
                            Nome = "Colaborador"
                        },
                        new
                        {
                            IdPerfil = 4,
                            DtCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtModificacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkIdUsuario = 4,
                            Nome = "Visualizador"
                        },
                        new
                        {
                            IdPerfil = 5,
                            DtCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtModificacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FkIdUsuario = 5,
                            Nome = "Supervisor"
                        });
                });

            modelBuilder.Entity("Empodera.Models.Permissoes", b =>
                {
                    b.Property<int>("IdPermissoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodeAtualizar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodeCriar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodeDeletar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodeDetalhar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PodeListar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPermissoes");

                    b.HasIndex("FkIdPerfil");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            IdPermissoes = 1,
                            FkIdPerfil = 1,
                            Modulo = "Usuarios",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 2,
                            FkIdPerfil = 1,
                            Modulo = "Perfis",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 3,
                            FkIdPerfil = 1,
                            Modulo = "Atividades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 4,
                            FkIdPerfil = 1,
                            Modulo = "Comunidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 5,
                            FkIdPerfil = 1,
                            Modulo = "Vulnerabilidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 6,
                            FkIdPerfil = 1,
                            Modulo = "Recursos",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 7,
                            FkIdPerfil = 1,
                            Modulo = "DiariosCampo",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 8,
                            FkIdPerfil = 1,
                            Modulo = "Atores",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 9,
                            FkIdPerfil = 1,
                            Modulo = "Ficha1Contato",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 10,
                            FkIdPerfil = 1,
                            Modulo = "DiariosProcessoPessoal",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 11,
                            FkIdPerfil = 1,
                            Modulo = "AvaliacoesPessoais",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 12,
                            FkIdPerfil = 1,
                            Modulo = "SER",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "S",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 13,
                            FkIdPerfil = 2,
                            Modulo = "Usuarios",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 14,
                            FkIdPerfil = 2,
                            Modulo = "Perfis",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 15,
                            FkIdPerfil = 2,
                            Modulo = "Atividades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 16,
                            FkIdPerfil = 2,
                            Modulo = "Comunidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 17,
                            FkIdPerfil = 2,
                            Modulo = "Vulnerabilidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 18,
                            FkIdPerfil = 2,
                            Modulo = "Recursos",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 19,
                            FkIdPerfil = 2,
                            Modulo = "DiariosCampo",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 20,
                            FkIdPerfil = 2,
                            Modulo = "Atores",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 21,
                            FkIdPerfil = 2,
                            Modulo = "Ficha1Contato",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 22,
                            FkIdPerfil = 2,
                            Modulo = "DiariosProcessoPessoal",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 23,
                            FkIdPerfil = 2,
                            Modulo = "AvaliacoesPessoais",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 24,
                            FkIdPerfil = 2,
                            Modulo = "SER",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 25,
                            FkIdPerfil = 3,
                            Modulo = "Usuarios",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 26,
                            FkIdPerfil = 3,
                            Modulo = "Perfis",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 27,
                            FkIdPerfil = 3,
                            Modulo = "Atividades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 28,
                            FkIdPerfil = 3,
                            Modulo = "Comunidades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 29,
                            FkIdPerfil = 3,
                            Modulo = "Vulnerabilidades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 30,
                            FkIdPerfil = 3,
                            Modulo = "Recursos",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 31,
                            FkIdPerfil = 3,
                            Modulo = "DiariosCampo",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 32,
                            FkIdPerfil = 3,
                            Modulo = "Atores",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 33,
                            FkIdPerfil = 3,
                            Modulo = "Ficha1Contato",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 34,
                            FkIdPerfil = 3,
                            Modulo = "DiariosProcessoPessoal",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 35,
                            FkIdPerfil = 3,
                            Modulo = "AvaliacoesPessoais",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 36,
                            FkIdPerfil = 3,
                            Modulo = "SER",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 37,
                            FkIdPerfil = 4,
                            Modulo = "Usuarios",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 38,
                            FkIdPerfil = 4,
                            Modulo = "Perfis",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 39,
                            FkIdPerfil = 4,
                            Modulo = "Atividades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 40,
                            FkIdPerfil = 4,
                            Modulo = "Comunidades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 41,
                            FkIdPerfil = 4,
                            Modulo = "Vulnerabilidades",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 42,
                            FkIdPerfil = 4,
                            Modulo = "Recursos",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 43,
                            FkIdPerfil = 4,
                            Modulo = "DiariosCampo",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 44,
                            FkIdPerfil = 4,
                            Modulo = "Atores",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 45,
                            FkIdPerfil = 4,
                            Modulo = "Ficha1Contato",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 46,
                            FkIdPerfil = 4,
                            Modulo = "DiariosProcessoPessoal",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 47,
                            FkIdPerfil = 4,
                            Modulo = "AvaliacoesPessoais",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 48,
                            FkIdPerfil = 4,
                            Modulo = "SER",
                            PodeAtualizar = "N",
                            PodeCriar = "N",
                            PodeDeletar = "N",
                            PodeDetalhar = "N",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 49,
                            FkIdPerfil = 5,
                            Modulo = "Usuarios",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 50,
                            FkIdPerfil = 5,
                            Modulo = "Perfis",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 51,
                            FkIdPerfil = 5,
                            Modulo = "Atividades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 52,
                            FkIdPerfil = 5,
                            Modulo = "Comunidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 53,
                            FkIdPerfil = 5,
                            Modulo = "Vulnerabilidades",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 54,
                            FkIdPerfil = 5,
                            Modulo = "Recursos",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 55,
                            FkIdPerfil = 5,
                            Modulo = "DiariosCampo",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 56,
                            FkIdPerfil = 5,
                            Modulo = "Atores",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 57,
                            FkIdPerfil = 5,
                            Modulo = "Ficha1Contato",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 58,
                            FkIdPerfil = 5,
                            Modulo = "DiariosProcessoPessoal",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 59,
                            FkIdPerfil = 5,
                            Modulo = "AvaliacoesPessoais",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        },
                        new
                        {
                            IdPermissoes = 60,
                            FkIdPerfil = 5,
                            Modulo = "SER",
                            PodeAtualizar = "S",
                            PodeCriar = "S",
                            PodeDeletar = "N",
                            PodeDetalhar = "S",
                            PodeListar = "S"
                        });
                });

            modelBuilder.Entity("Empodera.Models.RecursosAtores", b =>
                {
                    b.Property<int>("Id_Recursos_Atores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Recursos_Atores");

                    b.HasIndex("FK_id_Atores");

                    b.ToTable("RecursosAtores");
                });

            modelBuilder.Entity("Empodera.Models.RedeEixo", b =>
                {
                    b.Property<int>("IdRedeEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdEixo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdRede")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRedeEixo");

                    b.HasIndex("FkIdEixo");

                    b.HasIndex("FkIdRede");

                    b.ToTable("RedeEixos");
                });

            modelBuilder.Entity("Empodera.Models.RedePrimaria", b =>
                {
                    b.Property<int>("IdRedePrimaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAtorPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdAtorRelacionados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRedePrimaria");

                    b.HasIndex("FkIdAtorPrincipal");

                    b.HasIndex("FkIdAtorRelacionados");

                    b.ToTable("RedesPrimarias");
                });

            modelBuilder.Entity("Empodera.Models.RedeRecursos", b =>
                {
                    b.Property<int>("Id_Rede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dispositivo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtModificacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FK_id_Atores")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Rede");

                    b.HasIndex("FK_id_Atores");

                    b.HasIndex("FkIdComunidade");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("RedeRecursos");
                });

            modelBuilder.Entity("Empodera.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FkIdPerfil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("FkIdPerfil");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Ativo = "S",
                            DtAtualizacao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao@email.com",
                            FkIdPerfil = 1,
                            Foto = "foto1.jpg",
                            Genero = "Masculino",
                            Nome = "joao",
                            Ocupacao = "Coordenador",
                            Senha = "AQAAAAIAAYagAAAAEJcfohm0J9StjpodK4pthBMssFrYtCteqHFi8rtfIPs+0mjn9jbeYSGV2ri/Iq2tIA=="
                        },
                        new
                        {
                            IdUsuario = 2,
                            Ativo = "S",
                            DtAtualizacao = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtCriacao = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtNascimento = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "u2@example.com",
                            FkIdPerfil = 2,
                            Foto = "foto2.jpg",
                            Genero = "Feminino",
                            Nome = "Usuario Dois",
                            Ocupacao = "Pesquisador",
                            Senha = "AQAAAAIAAYagAAAAEJcfohm0J9StjpodK4pthBMssFrYtCteqHFi8rtfIPs+0mjn9jbeYSGV2ri/Iq2tIA=="
                        },
                        new
                        {
                            IdUsuario = 3,
                            Ativo = "S",
                            DtAtualizacao = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtCriacao = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtNascimento = new DateTime(1995, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "u3@example.com",
                            FkIdPerfil = 3,
                            Foto = "foto3.jpg",
                            Genero = "Masculino",
                            Nome = "Usuario Tres",
                            Ocupacao = "Voluntario",
                            Senha = "AQAAAAIAAYagAAAAEJcfohm0J9StjpodK4pthBMssFrYtCteqHFi8rtfIPs+0mjn9jbeYSGV2ri/Iq2tIA=="
                        },
                        new
                        {
                            IdUsuario = 4,
                            Ativo = "N",
                            DtAtualizacao = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtCriacao = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtNascimento = new DateTime(1992, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "u4@example.com",
                            FkIdPerfil = 4,
                            Foto = "foto4.jpg",
                            Genero = "Feminino",
                            Nome = "Usuario Quatro",
                            Ocupacao = "Analista",
                            Senha = "AQAAAAIAAYagAAAAEJcfohm0J9StjpodK4pthBMssFrYtCteqHFi8rtfIPs+0mjn9jbeYSGV2ri/Iq2tIA=="
                        },
                        new
                        {
                            IdUsuario = 5,
                            Ativo = "N",
                            DtAtualizacao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtCriacao = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtNascimento = new DateTime(1988, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "u5@example.com",
                            FkIdPerfil = 5,
                            Foto = "foto5.jpg",
                            Genero = "Masculino",
                            Nome = "Usuario Cinco",
                            Ocupacao = "Gerente",
                            Senha = "AQAAAAIAAYagAAAAEJcfohm0J9StjpodK4pthBMssFrYtCteqHFi8rtfIPs+0mjn9jbeYSGV2ri/Iq2tIA=="
                        });
                });

            modelBuilder.Entity("Empodera.Models.Vulnerabilidade", b =>
                {
                    b.Property<int>("IdVulnerabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdComunidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdVulnerabilidade");

                    b.HasIndex("FkIdComunidade");

                    b.ToTable("Vulnerabilidades");
                });

            modelBuilder.Entity("Empodera.Models.VulnerabilidadesEixo", b =>
                {
                    b.Property<int>("IdVEixo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdEixo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FkIdVulnerabilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVEixo");

                    b.HasIndex("FkIdEixo");

                    b.HasIndex("FkIdVulnerabilidade");

                    b.ToTable("VulnerabilidadesEixo");
                });

            modelBuilder.Entity("Empodera.Models.Acoes", b =>
                {
                    b.HasOne("Empodera.Models.Atividades", "Atividades")
                        .WithMany("Acoes")
                        .HasForeignKey("FkIdAtividade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("Empodera.Models.AcoesAtores", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("AcoesAtores")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Acoes", "Acoes")
                        .WithMany("AcoesAtores")
                        .HasForeignKey("FkIdAcoes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acoes");

                    b.Navigation("Ator");
                });

            modelBuilder.Entity("Empodera.Models.AnexosDiario", b =>
                {
                    b.HasOne("Empodera.Models.DiarioCampo", "Diario")
                        .WithMany("Anexos")
                        .HasForeignKey("FkIdDiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diario");
                });

            modelBuilder.Entity("Empodera.Models.Atividades", b =>
                {
                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("Atividades")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("Atividades")
                        .HasForeignKey("FkIdUsuarioM")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comunidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.AtividadesEixo", b =>
                {
                    b.HasOne("Empodera.Models.Atividades", "Atividades")
                        .WithMany("AtividadesEixos")
                        .HasForeignKey("FkIdAtividade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Eixo", "Eixo")
                        .WithMany("AtividadesEixo")
                        .HasForeignKey("FkIdEixo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividades");

                    b.Navigation("Eixo");
                });

            modelBuilder.Entity("Empodera.Models.AtorComunidade", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("Comunidades")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("AtorComunidades")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Comunidade");
                });

            modelBuilder.Entity("Empodera.Models.Atores", b =>
                {
                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("Atores")
                        .HasForeignKey("FkIdUsuarioM")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.AvaliacaoPessoal", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.Comunidade", b =>
                {
                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("Comunidades")
                        .HasForeignKey("FK_Id_UsuarioM")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.DAAtores", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("DAAtores")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.DiarioDAcoes", "DiarioDAcoes")
                        .WithMany("DAtores")
                        .HasForeignKey("FkIdDDacoes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("DiarioDAcoes");
                });

            modelBuilder.Entity("Empodera.Models.DetalhesDAcoes", b =>
                {
                    b.HasOne("Empodera.Models.DiarioDAcoes", "DiarioDAcoes")
                        .WithMany("Detalhes")
                        .HasForeignKey("FkIdDDacoes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiarioDAcoes");
                });

            modelBuilder.Entity("Empodera.Models.DetalhesEixos", b =>
                {
                    b.HasOne("Empodera.Models.DetalhesDAcoes", "Detalhes")
                        .WithMany("DetalhesEixos")
                        .HasForeignKey("FkIdDetalhes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Eixo", "Eixo")
                        .WithMany("DetalhesEixos")
                        .HasForeignKey("FkIdEixo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");

                    b.Navigation("Eixo");
                });

            modelBuilder.Entity("Empodera.Models.DiarioAcoes", b =>
                {
                    b.HasOne("Empodera.Models.Acoes", "Acoes")
                        .WithMany("DiarioAcoes")
                        .HasForeignKey("FkIdAcoes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.DiarioCampo", "Diario")
                        .WithMany("DiarioAcoes")
                        .HasForeignKey("FkIdDiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acoes");

                    b.Navigation("Diario");
                });

            modelBuilder.Entity("Empodera.Models.DiarioCampo", b =>
                {
                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("DiarioCampos")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("DiarioCampos")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Comunidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.DiarioDAcoes", b =>
                {
                    b.HasOne("Empodera.Models.DiarioCampo", "Diario")
                        .WithMany("DiarioDAcoes")
                        .HasForeignKey("FkIdDiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diario");
                });

            modelBuilder.Entity("Empodera.Models.DiarioEixo", b =>
                {
                    b.HasOne("Empodera.Models.DiarioCampo", "Diario")
                        .WithMany("DiarioEixos")
                        .HasForeignKey("FkIdDiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Eixo", "Eixo")
                        .WithMany("DiarioEixos")
                        .HasForeignKey("FkIdEixo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diario");

                    b.Navigation("Eixo");
                });

            modelBuilder.Entity("Empodera.Models.FichaCondicoes", b =>
                {
                    b.HasOne("Empodera.Models.FichaPrimeiroContato", "Ficha")
                        .WithMany("FichaCondicoes")
                        .HasForeignKey("FkIdFicha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("Empodera.Models.FichaPeticoes", b =>
                {
                    b.HasOne("Empodera.Models.FichaPrimeiroContato", "Ficha")
                        .WithMany("FichaPeticoes")
                        .HasForeignKey("FkIdFicha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("Empodera.Models.FichaPrimeiroContato", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("FichasPrimeiroContato")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("FichasPrimeiroContato")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("FichasPrimeiroContato")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Comunidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.FichaResp", b =>
                {
                    b.HasOne("Empodera.Models.FichaPrimeiroContato", "Ficha")
                        .WithMany("FichaRespostas")
                        .HasForeignKey("FkIdFicha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("Empodera.Models.FichaResult", b =>
                {
                    b.HasOne("Empodera.Models.FichaPrimeiroContato", "Ficha")
                        .WithMany("FichaResultados")
                        .HasForeignKey("FkIdFicha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("Empodera.Models.FonteInf", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("FonteInfos")
                        .HasForeignKey("AtorIdAtores");

                    b.HasOne("Empodera.Models.FichaPrimeiroContato", "Ficha")
                        .WithMany("Fontes")
                        .HasForeignKey("FkIdFicha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Ficha");
                });

            modelBuilder.Entity("Empodera.Models.Permissoes", b =>
                {
                    b.HasOne("Empodera.Models.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("FkIdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Empodera.Models.RecursosAtores", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Atores")
                        .WithMany("RecursosAtores")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atores");
                });

            modelBuilder.Entity("Empodera.Models.RedeEixo", b =>
                {
                    b.HasOne("Empodera.Models.Eixo", "Eixo")
                        .WithMany("RedeEixos")
                        .HasForeignKey("FkIdEixo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.RedeRecursos", "RedeRecursos")
                        .WithMany("RedeEixos")
                        .HasForeignKey("FkIdRede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eixo");

                    b.Navigation("RedeRecursos");
                });

            modelBuilder.Entity("Empodera.Models.RedePrimaria", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "AtorPrincipal")
                        .WithMany()
                        .HasForeignKey("FkIdAtorPrincipal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Atores", "AtorRelacionado")
                        .WithMany()
                        .HasForeignKey("FkIdAtorRelacionados")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtorPrincipal");

                    b.Navigation("AtorRelacionado");
                });

            modelBuilder.Entity("Empodera.Models.RedeRecursos", b =>
                {
                    b.HasOne("Empodera.Models.Atores", "Ator")
                        .WithMany("Redes")
                        .HasForeignKey("FK_id_Atores")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("RedeRecursos")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Usuario", "Usuario")
                        .WithMany("RedeRecursos")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Comunidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Empodera.Models.Usuario", b =>
                {
                    b.HasOne("Empodera.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("FkIdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Empodera.Models.Vulnerabilidade", b =>
                {
                    b.HasOne("Empodera.Models.Comunidade", "Comunidade")
                        .WithMany("Vulnerabilidades")
                        .HasForeignKey("FkIdComunidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunidade");
                });

            modelBuilder.Entity("Empodera.Models.VulnerabilidadesEixo", b =>
                {
                    b.HasOne("Empodera.Models.Eixo", "Eixo")
                        .WithMany("VulnerabilidadesEixos")
                        .HasForeignKey("FkIdEixo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empodera.Models.Vulnerabilidade", "Vulnerabilidade")
                        .WithMany("VulnerabilidadesEixos")
                        .HasForeignKey("FkIdVulnerabilidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eixo");

                    b.Navigation("Vulnerabilidade");
                });

            modelBuilder.Entity("Empodera.Models.Acoes", b =>
                {
                    b.Navigation("AcoesAtores");

                    b.Navigation("DiarioAcoes");
                });

            modelBuilder.Entity("Empodera.Models.Atividades", b =>
                {
                    b.Navigation("Acoes");

                    b.Navigation("AtividadesEixos");
                });

            modelBuilder.Entity("Empodera.Models.Atores", b =>
                {
                    b.Navigation("AcoesAtores");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Comunidades");

                    b.Navigation("DAAtores");

                    b.Navigation("FichasPrimeiroContato");

                    b.Navigation("FonteInfos");

                    b.Navigation("RecursosAtores");

                    b.Navigation("Redes");
                });

            modelBuilder.Entity("Empodera.Models.Comunidade", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("AtorComunidades");

                    b.Navigation("DiarioCampos");

                    b.Navigation("FichasPrimeiroContato");

                    b.Navigation("RedeRecursos");

                    b.Navigation("Vulnerabilidades");
                });

            modelBuilder.Entity("Empodera.Models.DetalhesDAcoes", b =>
                {
                    b.Navigation("DetalhesEixos");
                });

            modelBuilder.Entity("Empodera.Models.DiarioCampo", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("DiarioAcoes");

                    b.Navigation("DiarioDAcoes");

                    b.Navigation("DiarioEixos");
                });

            modelBuilder.Entity("Empodera.Models.DiarioDAcoes", b =>
                {
                    b.Navigation("DAtores");

                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("Empodera.Models.Eixo", b =>
                {
                    b.Navigation("AtividadesEixo");

                    b.Navigation("DetalhesEixos");

                    b.Navigation("DiarioEixos");

                    b.Navigation("RedeEixos");

                    b.Navigation("VulnerabilidadesEixos");
                });

            modelBuilder.Entity("Empodera.Models.FichaPrimeiroContato", b =>
                {
                    b.Navigation("FichaCondicoes");

                    b.Navigation("FichaPeticoes");

                    b.Navigation("FichaRespostas");

                    b.Navigation("FichaResultados");

                    b.Navigation("Fontes");
                });

            modelBuilder.Entity("Empodera.Models.Perfil", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Empodera.Models.RedeRecursos", b =>
                {
                    b.Navigation("RedeEixos");
                });

            modelBuilder.Entity("Empodera.Models.Usuario", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Atores");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Comunidades");

                    b.Navigation("DiarioCampos");

                    b.Navigation("FichasPrimeiroContato");

                    b.Navigation("RedeRecursos");
                });

            modelBuilder.Entity("Empodera.Models.Vulnerabilidade", b =>
                {
                    b.Navigation("VulnerabilidadesEixos");
                });
#pragma warning restore 612, 618
        }
    }
}
